version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: quanlykho-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: quanlykho
    ports:
      - "5432:5432" # Standard PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - quanlykho-network

  redis:
    image: redis:alpine
    container_name: quanlykho-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - quanlykho-network

networks:
  quanlykho-network:
    driver: bridge

volumes:
  db_data:
  redis_data:
